version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: erp-postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker_password
      POSTGRES_DB: erp_api
    ports:
      - "5432:5432"
    volumes:
      - erp_pgdata:/var/lib/postgresql/data

volumes:
  erp_pgdata:
